version: '3'
services:
  flask:
    build: .
    ports:
      - "19998:5000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: obugs
      POSTGRES_USER: obugs
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../obugs_postgres_data:/var/lib/postgresql/data
