services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: obugs-backend

    container_name: obugs-backend-server
    restart: always
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "19998:5000"

  db:
    image: postgres:latest

    container_name: obugs-backend-db
    restart: always

    environment:
      POSTGRES_DB: obugs
      POSTGRES_USER: obugs
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U obugs" ]
      interval: 5s
      timeout: 5s
      retries: 5
