services:
  db:
    image: postgres:latest

    container_name: obugs-backend-dev-db
    restart: always

    environment:
      POSTGRES_DB: obugs
      POSTGRES_USER: obugs
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
