"""empty message

Revision ID: 47dd3f359556
Revises: 82d72fe26022
Create Date: 2023-12-01 11:27:20.481084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

from obugs.database.entry import Entry
from obugs.database.entry_message import EntryMessageComment

# revision identifiers, used by Alembic.
revision: str = '47dd3f359556'
down_revision: Union[str, None] = '82d72fe26022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('comment_count', sa.Integer(), nullable=True))

    # Compute comment_count for each entry
    session = Session(bind=op.get_bind())
    for entry in session.query(Entry).all():
        entry.comment_count = session.query(EntryMessageComment).where(EntryMessageComment.entry == entry).count()
    session.commit()

    op.alter_column('entry', 'comment_count', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'comment_count')
    # ### end Alembic commands ###
