"""empty message

Revision ID: 6bf7732c1a3f
Revises: e45ea3e85810
Create Date: 2023-10-11 13:32:19.132728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf7732c1a3f'
down_revision: Union[str, None] = 'e45ea3e85810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_suggestion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entry_software_and_title', 'entry', ['software_id', 'title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_entry_software_and_title', table_name='entry')
    op.drop_table('software_suggestion')
    # ### end Alembic commands ###
