"""empty message

Revision ID: 82d72fe26022
Revises: 0999797c9ca6
Create Date: 2023-11-07 14:20:45.909396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d72fe26022'
down_revision: Union[str, None] = '0999797c9ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('software_suggestion', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'software_suggestion', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'software_suggestion', type_='foreignkey')
    op.drop_column('software_suggestion', 'user_id')
    # ### end Alembic commands ###
