"""empty message

Revision ID: e45ea3e85810
Revises: 86a86e9e5a90
Create Date: 2023-10-04 12:57:10.234806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45ea3e85810'
down_revision: Union[str, None] = '86a86e9e5a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('rating', sa.Float(), nullable=True))
    op.execute("""UPDATE entry SET rating = rating_total / rating_count WHERE rating IS NULL""")
    op.alter_column('entry', 'rating', nullable=False)
    op.create_index('idx_tag_software_id_name', 'tag', ['software_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tag_software_id_name', table_name='tag')
    op.drop_column('entry', 'rating')
    # ### end Alembic commands ###
