"""empty message

Revision ID: f4402ea7d8f8
Revises: 5175b048d27e
Create Date: 2023-10-21 17:05:15.585928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4402ea7d8f8'
down_revision: Union[str, None] = '6bf7732c1a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_github_id'), 'user', ['github_id'], unique=False)
    op.add_column('user', sa.Column('github_name', sa.String(), nullable=True))
    op.drop_column('user', 'activation_token')
    op.drop_column('user', 'is_activated')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'github_name')
    op.drop_index(op.f('ix_user_github_id'), table_name='user')
    op.drop_column('user', 'github_id')
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_activated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('activation_token', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
