# Generated by Django 4.1.7 on 2023-02-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='NEW', max_length=50)),
                ('rating_total', models.IntegerField(default=2)),
                ('rating_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('editor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.software')),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('field', models.CharField(default='title', max_length=50)),
                ('value', models.TextField()),
                ('rating', models.IntegerField(default=1)),
                ('rating_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bug')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='BugVote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=2)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='BugPetitionVotes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=1)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.petition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='BugComment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bug')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.user')),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.software'),
        ),
        migrations.AddField(
            model_name='bug',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.user'),
        ),
    ]
